/*
    THIS IS A GENERATED FILE
    Changes might be overwritten in the future, edit with caution!
*/

export const Tables = {
	Users: 'Users',
	Customers: 'Customers',
	Invoices: 'Invoices',
	Payments: 'Payments',
	CustomerUpdates: 'Customer Updates',
	MeterReadings: 'Meter Readings',
	Sites: 'Sites',
	TariffPlans: 'Tariff Plans',
	Inventory: 'Inventory',
	InventoryUpdates: 'Inventory Updates',
	Incidents: 'Incidents',
	IncidentUpdates: 'Incident Updates',
	Maintenance: 'Maintenance',
	FinancialReport: 'Financial Report',
};

export const Columns = {
	"Users": {
		အမည်: {name:`အမည်`, type:`text`},
		email: {name:`Email`, type:`text`},
		photo: {name:`Photo`, type:`multipleAttachment`},
		incidentIds: {name:`Incidents`, type:`foreignKey-many`},
		siteIds: {name:`Site`, type:`foreignKey-many`},
		password: {name:`Password`, type:`text`},
		name: {name:`Name`, type:`text`},
		username: {name:`Username`, type:`text`},
		customers: {name:`Customers`, type:`lookup`},
	},
	"Customers": {
		အမည်: {name:`အမည်`, type:`text`},
		name: {name:`Name`, type:`text`},
		meterNumber: {name:`Meter Number`, type:`number`},
		tariffPlansId: {name:`Tariff Plans`, type:`foreignKey-one`},
		customerUpdateIds: {name:`Customer Updates`, type:`foreignKey-many`},
		sitesId: {name:`Sites`, type:`foreignKey-one`},
		isactive: {name:`IsActive`, type:`checkbox`},
		hasmeter: {name:`HasMeter`, type:`checkbox`},
		invoiceIds: {name:`Invoices`, type:`foreignKey-many`},
		paymentIds: {name:`Payments`, type:`foreignKey-many`},
		outstandingPayment: {name:`Outstanding Payment`, type:`formula`},
		meterReadingIds: {name:`Meter Readings`, type:`foreignKey-many`},
		startingDate: {name:`Starting Date`, type:`date`},
		amountfromInvoices: {name:`Amount (from Invoices)`, type:`lookup`},
		amountfromPayments: {name:`Amount (from Payments)`, type:`lookup`},
		currentPeriodfromSites: {name:`Current Period (from Sites)`, type:`lookup`},
		haspaid: {name:`HasPaid`, type:`formula`},
		latestMeterReadingDate: {name:`Latest Meter Reading Date`, type:`rollup`},
		latestPaymentDate: {name:`Latest Payment Date`, type:`rollup`},
		latestInvoiceDate: {name:`Latest Invoice Date`, type:`rollup`},
		periodStartDate: {name:`Period Start Date`, type:`lookup`},
		periodEndDate: {name:`Period End Date`, type:`lookup`},
		isbilled: {name:`IsBilled`, type:`formula`},
		previousMeterReadingDate: {name:`Previous Meter Reading Date`, type:`rollup`},
		latestMeterReading: {name:`Latest Meter Reading`, type:`lookup`},
		previousMeterReading: {name:`Previous Meter Reading`, type:`lookup`},
		electricityUsage: {name:`Electricity Usage`, type:`formula`},
		needsReading: {name:`Needs Reading`, type:`formula`},
	},
	"Invoices": {
		name: {name:`Name`, type:`formula`},
		amount: {name:`Amount`, type:`number`},
		date: {name:`Date`, type:`date`},
		period: {name:`Period`, type:`number`},
		customerId: {name:`Customer`, type:`foreignKey-one`},
		currentPeriodfromSitesfromCustomers: {name:`Current Period (from Sites) (from Customers)`, type:`lookup`},
		isCurrentPeriod: {name:`Is Current Period`, type:`formula`},
	},
	"Payments": {
		name: {name:`Name`, type:`formula`},
		amount: {name:`Amount`, type:`number`},
		period: {name:`Period`, type:`number`},
		date: {name:`Date`, type:`date`},
		customerId: {name:`Customer`, type:`foreignKey-one`},
		isCurrentPeriod: {name:`Is Current Period`, type:`formula`},
		currentPeriodfromSitesfromCustomers: {name:`Current Period (from Sites) (from Customers)`, type:`lookup`},
	},
	"Customer Updates": {
		updateId: {name:`Update Id`, type:`autoNumber`},
		explanation: {name:`Explanation`, type:`multilineText`},
		dateUpdated: {name:`Date Updated`, type:`date`},
		customerId: {name:`Customer`, type:`foreignKey-one`},
	},
	"Meter Readings": {
		name: {name:`Name`, type:`autoNumber`},
		date: {name:`Date`, type:`date`},
		reading: {name:`Reading`, type:`number`},
		period: {name:`Period`, type:`number`},
		customerId: {name:`Customer`, type:`foreignKey-one`},
		latestMeterReadingDate: {name:`Latest Meter Reading Date`, type:`lookup`},
		isLatestMeterReading: {name:`Is Latest Meter Reading`, type:`formula`},
		isOldMeterReading: {name:`Is Old Meter Reading`, type:`formula`},
		previousMeterReadingDate: {name:`Previous Meter Reading Date`, type:`lookup`},
		isPreviousMeterReading: {name:`Is Previous Meter Reading`, type:`formula`},
	},
	"Sites": {
		name: {name:`Name`, type:`text`},
		incidentIds: {name:`Incidents`, type:`foreignKey-many`},
		inventoryIds: {name:`Inventory`, type:`foreignKey-many`},
		inventoryUpdateIds: {name:`Inventory Updates`, type:`foreignKey-many`},
		tariffPlanIds: {name:`Tariff Plans`, type:`foreignKey-many`},
		userIds: {name:`Users`, type:`foreignKey-many`},
		customerIds: {name:`Customers`, type:`foreignKey-many`},
		currentPeriod: {name:`Current Period`, type:`number`},
		financialReportIds: {name:`Financial Report`, type:`foreignKey-many`},
		totalNumCustomers: {name:`Total Num Customers`, type:`count`},
		totalOutstandingPayments: {name:`Total Outstanding Payments`, type:`rollup`},
		numActiveCustomers: {name:`Num Active Customers`, type:`count`},
		periodStartDate: {name:`Period Start Date`, type:`date`},
		periodEndDate: {name:`Period End Date`, type:`date`},
		expenses: {name:`Expenses`, type:`rollup`},
		numPaidCustomers: {name:`Num Paid Customers`, type:`rollup`},
		amountCollected: {name:`Amount Collected`, type:`rollup`},
		numBilledCustomers: {name:`Num Billed Customers`, type:`rollup`},
		totalElectricityUsage: {name:`Total Electricity Usage`, type:`rollup`},
		totalTariffsCharged: {name:`Total Tariffs Charged`, type:`rollup`},
		numNeedsReading: {name:`Num Needs Reading`, type:`rollup`},
		numCustomersNeedPay: {name:`Num Customers Need Pay`, type:`formula`},
	},
	"Tariff Plans": {
		name: {name:`Name`, type:`text`},
		fixedTariff: {name:`Fixed Tariff`, type:`number`},
		tariffByUnit: {name:`Tariff By Unit`, type:`number`},
		minUnits: {name:`Min Units`, type:`number`},
		siteIds: {name:`Site`, type:`foreignKey-many`},
		customerIds: {name:`Customer`, type:`foreignKey-many`},
	},
	"Inventory": {
		name: {name:`Name`, type:`text`},
		quantity: {name:`Quantity`, type:`number`},
		siteId: {name:`Site`, type:`foreignKey-one`},
		quantityUnit: {name:`Quantity Unit`, type:`multilineText`},
		inventoryUpdateIds: {name:`Inventory Updates`, type:`foreignKey-many`},
		lastUpdatedDatefromInventoryUpdates: {name:`Last Updated Date(from Inventory Updates)`, type:`rollup`},
	},
	"Inventory Updates": {
		name: {name:`Name`, type:`text`},
		quantity: {name:`Quantity`, type:`number`},
		receiptPhoto: {name:`Receipt Photo`, type:`multipleAttachment`},
		inventoryItemId: {name:`Inventory Item`, type:`foreignKey-one`},
		adminApproved: {name:`Admin Approved`, type:`checkbox`},
		siteId: {name:`Site`, type:`foreignKey-one`},
		amountPaid: {name:`Amount Paid`, type:`number`},
		notes: {name:`Notes`, type:`multilineText`},
		dateRecorded: {name:`Date Recorded`, type:`date`},
		isInCurrentPeriod: {name:`Is In Current Period`, type:`formula`},
		periodStartDate: {name:`Period Start Date`, type:`lookup`},
		periodEndDate: {name:`Period End Date`, type:`lookup`},
	},
	"Incidents": {
		incidentId: {name:`Incident Id`, type:`autoNumber`},
		description: {name:`Description`, type:`multilineText`},
		incidentPhotos: {name:`Incident Photos`, type:`multipleAttachment`},
		status: {name:`Status`, type:`select`},
		incidentUpdateIds: {name:`Incident Updates`, type:`foreignKey-many`},
		isResolved: {name:`Is Resolved`, type:`checkbox`},
		resolutionDate: {name:`Resolution Date`, type:`date`},
		resolutionDescription: {name:`Resolution Description`, type:`multilineText`},
		resolutionPhoto: {name:`Resolution Photo`, type:`multipleAttachment`},
		dateRecorded: {name:`Date Recorded`, type:`date`},
		siteId: {name:`Site`, type:`foreignKey-one`},
		userId: {name:`User`, type:`foreignKey-one`},
		category: {name:`Category`, type:`multiSelect`},
		name: {name:`Name`, type:`text`},
	},
	"Incident Updates": {
		updateId: {name:`Update Id`, type:`autoNumber`},
		description: {name:`Description`, type:`multilineText`},
		photos: {name:`Photos`, type:`multipleAttachment`},
		dateRecorded: {name:`Date Recorded`, type:`date`},
		incidentId: {name:`Incident`, type:`foreignKey-one`},
	},
	"Maintenance": {
		taskDescription: {name:`Task Description`, type:`multilineText`},
		frequency: {name:`Frequency`, type:`select`},
		equipment: {name:`Equipment`, type:`select`},
	},
	"Financial Report": {
		name: {name:`Name`, type:`text`},
		electricityUsage: {name:`Electricity Usage`, type:`lookup`},
		tariffsCharged: {name:`Tariffs Charged`, type:`lookup`},
		numBilledCustomers: {name:`Num Billed Customers`, type:`lookup`},
		totalProfit: {name:`Total Profit`, type:`formula`},
		lastUpdated: {name:`Last Updated`, type:`date`},
		period: {name:`Period`, type:`lookup`},
		bankSlip: {name:`Bank Slip`, type:`multipleAttachment`},
		paymentApproved: {name:`Payment Approved`, type:`checkbox`},
		reportApproved: {name:`Report Approved`, type:`checkbox`},
		sitesId: {name:`Sites`, type:`foreignKey-one`},
		numTotalCustomers: {name:`Num Total Customers`, type:`lookup`},
		totalOutstandingPayments: {name:`Total Outstanding Payments`, type:`lookup`},
		numActiveCustomers: {name:`Num Active Customers`, type:`lookup`},
		totalExpenses: {name:`Total Expenses`, type:`lookup`},
		numPaidCustomers: {name:`Num Paid Customers`, type:`lookup`},
		amountCollected: {name:`Amount Collected`, type:`lookup`},
		numNeedsReading: {name:`Num Needs Reading`, type:`lookup`},
		numCustomersNeedPay: {name:`Num Customers Need Pay`, type:`lookup`},
	},
};
