/*
    THIS IS A GENERATED FILE
    Changes might be overwritten in the future, edit with caution!
*/

export const Tables = {
	Users: 'Users',
	Customers: 'Customers',
	Invoices: 'Invoices',
	Payments: 'Payments',
	CustomerUpdates: 'Customer Updates',
	MeterReadings: 'Meter Readings',
	Sites: 'Sites',
	TariffPlans: 'Tariff Plans',
	Inventory: 'Inventory',
	InventoryUpdates: 'Inventory Updates',
	Incidents: 'Incidents',
	IncidentUpdates: 'Incident Updates',
	Maintenance: 'Maintenance',
	FinancialReport: 'Financial Report',
};

export const Columns = {
	"Users": {
		အမည်: {name:`အမည်`, type:`text`},
		email: {name:`Email`, type:`text`},
		photo: {name:`Photo`, type:`multipleAttachment`},
		incidentIds: {name:`Incidents`, type:`foreignKey-many`},
		sitIds: {name:`Site`, type:`foreignKey-many`},
		password: {name:`Password`, type:`text`},
		name: {name:`Name`, type:`text`},
		customerIds: {name:`Customers`, type:`foreignKey-many`},
	},
	"Customers": {
		အမည်: {name:`အမည်`, type:`text`},
		name: {name:`Name`, type:`text`},
		meterNumber: {name:`Meter Number`, type:`number`},
		tariffPlansId: {name:`Tariff Plans`, type:`foreignKey-one`},
		customerUpdateIds: {name:`Customer Updates`, type:`foreignKey-many`},
		siteIds: {name:`Sites`, type:`foreignKey-many`},
		isactive: {name:`IsActive`, type:`checkbox`},
		meter: {name:`Meter`, type:`checkbox`},
		invoiceIds: {name:`Invoices`, type:`foreignKey-many`},
		paymentIds: {name:`Payments`, type:`foreignKey-many`},
		outstandingPayment: {name:`Outstanding Payment`, type:`formula`},
		useIds: {name:`User`, type:`foreignKey-many`},
		meterReadingIds: {name:`Meter Readings`, type:`foreignKey-many`},
		startingDate: {name:`Starting Date`, type:`date`},
		amountfromInvoices: {name:`Amount (from Invoices)`, type:`lookup`},
		amountfromPayments: {name:`Amount (from Payments)`, type:`lookup`},
		currentPeriodfromSites: {name:`Current Period (from Sites)`, type:`lookup`},
		financialReport: {name:`Financial Report`, type:`text`},
		financialReport2: {name:`Financial Report 2`, type:`text`},
		financialReport3: {name:`Financial Report 3`, type:`text`},
	},
	"Invoices": {
		name: {name:`Name`, type:`formula`},
		amount: {name:`Amount`, type:`number`},
		date: {name:`Date`, type:`date`},
		period: {name:`Period`, type:`number`},
		customeIds: {name:`Customer`, type:`foreignKey-many`},
		currentPeriodfromSitesfromCustomers: {name:`Current Period (from Sites) (from Customers)`, type:`lookup`},
		isCurrentPeriod: {name:`Is Current Period`, type:`formula`},
	},
	"Payments": {
		name: {name:`Name`, type:`formula`},
		amount: {name:`Amount`, type:`number`},
		period: {name:`Period`, type:`number`},
		date: {name:`Date`, type:`date`},
		customeIds: {name:`Customer`, type:`foreignKey-many`},
		isCurrentPeriod: {name:`Is Current Period`, type:`formula`},
		currentPeriodfromSitesfromCustomers: {name:`Current Period (from Sites) (from Customers)`, type:`lookup`},
	},
	"Customer Updates": {
		updateId: {name:`Update Id`, type:`autoNumber`},
		explanation: {name:`Explanation`, type:`multilineText`},
		dateUpdated: {name:`Date Updated`, type:`date`},
		customerId: {name:`Customer`, type:`foreignKey-one`},
	},
	"Meter Readings": {
		name: {name:`Name`, type:`autoNumber`},
		date: {name:`Date`, type:`date`},
		reading: {name:`Reading`, type:`number`},
		period: {name:`Period`, type:`number`},
		customerId: {name:`Customer`, type:`foreignKey-one`},
	},
	"Sites": {
		name: {name:`Name`, type:`text`},
		incidentIds: {name:`Incidents`, type:`foreignKey-many`},
		inventorIds: {name:`Inventory`, type:`foreignKey-many`},
		inventoryUpdateIds: {name:`Inventory Updates`, type:`foreignKey-many`},
		tariffPlanIds: {name:`Tariff Plans`, type:`foreignKey-many`},
		userIds: {name:`Users`, type:`foreignKey-many`},
		customerIds: {name:`Customers`, type:`foreignKey-many`},
		financialReporIds: {name:`Financial Report`, type:`foreignKey-many`},
		startingDate: {name:`Starting Date`, type:`number`},
		currentPeriod: {name:`Current Period`, type:`number`},
	},
	"Tariff Plans": {
		name: {name:`Name`, type:`text`},
		fixedTariff: {name:`Fixed Tariff`, type:`number`},
		tariffByUnit: {name:`Tariff By Unit`, type:`number`},
		minUnits: {name:`Min Units`, type:`number`},
		sitIds: {name:`Site`, type:`foreignKey-many`},
		customeIds: {name:`Customer`, type:`foreignKey-many`},
		financialReporIds: {name:`Financial Report`, type:`foreignKey-many`},
	},
	"Inventory": {
		name: {name:`Name`, type:`text`},
		quantity: {name:`Quantity`, type:`number`},
		siteId: {name:`Site`, type:`foreignKey-one`},
		quantityUnit: {name:`Quantity Unit`, type:`multilineText`},
		inventoryUpdateIds: {name:`Inventory Updates`, type:`foreignKey-many`},
		lastUpdatedDatefromInventoryUpdates: {name:`Last Updated Date(from Inventory Updates)`, type:`rollup`},
	},
	"Inventory Updates": {
		name: {name:`Name`, type:`text`},
		quantity: {name:`Quantity`, type:`number`},
		receiptPhoto: {name:`Receipt Photo`, type:`multipleAttachment`},
		inventoryIteIds: {name:`Inventory Item`, type:`foreignKey-many`},
		adminApproved: {name:`Admin Approved`, type:`checkbox`},
		siteId: {name:`Site`, type:`foreignKey-one`},
		amountPaid: {name:`Amount Paid`, type:`number`},
		notes: {name:`Notes`, type:`multilineText`},
		dateRecorded: {name:`Date Recorded`, type:`date`},
		period: {name:`Period`, type:`lookup`},
	},
	"Incidents": {
		incidentId: {name:`Incident Id`, type:`autoNumber`},
		description: {name:`Description`, type:`multilineText`},
		incidentPhotos: {name:`Incident Photos`, type:`multipleAttachment`},
		status: {name:`Status`, type:`select`},
		incidentUpdateIds: {name:`Incident Updates`, type:`foreignKey-many`},
		isResolved: {name:`Is Resolved`, type:`checkbox`},
		resolutionDate: {name:`Resolution Date`, type:`date`},
		resolutionDescription: {name:`Resolution Description`, type:`multilineText`},
		resolutionPhoto: {name:`Resolution Photo`, type:`multipleAttachment`},
		dateRecorded: {name:`Date Recorded`, type:`date`},
		siteId: {name:`Site`, type:`foreignKey-one`},
		userId: {name:`User`, type:`foreignKey-one`},
		category: {name:`Category`, type:`multiSelect`},
		name: {name:`Name`, type:`text`},
	},
	"Incident Updates": {
		updateId: {name:`Update Id`, type:`autoNumber`},
		description: {name:`Description`, type:`multilineText`},
		photos: {name:`Photos`, type:`multipleAttachment`},
		dateRecorded: {name:`Date Recorded`, type:`date`},
		incidentId: {name:`Incident`, type:`foreignKey-one`},
	},
	"Maintenance": {
		taskDescription: {name:`Task Description`, type:`multilineText`},
		frequency: {name:`Frequency`, type:`select`},
		equipment: {name:`Equipment`, type:`select`},
	},
	"Financial Report": {
		name: {name:`Name`, type:`text`},
		sitIds: {name:`Site`, type:`foreignKey-many`},
		electricityUsage: {name:`Electricity Usage`, type:`number`},
		tariffsChargeIds: {name:`Tariffs Charged`, type:`foreignKey-many`},
		billed: {name:`Billed`, type:`number`},
		expenses: {name:`Expenses`, type:`number`},
		outstandingPayments: {name:`Outstanding Payments`, type:`number`},
		numActiveCustomers: {name:`Num Active Customers`, type:`number`},
		numBilledCustomers: {name:`Num Billed Customers`, type:`number`},
		numPaidCustomers: {name:`Num Paid Customers`, type:`number`},
		collected: {name:`Collected`, type:`number`},
		totalProfit: {name:`Total Profit`, type:`number`},
		lastUpdated: {name:`Last Updated`, type:`date`},
		period: {name:`Period`, type:`number`},
		numTotalCustomers: {name:`Num Total Customers`, type:`rollup`},
		bankSlip: {name:`Bank Slip`, type:`multipleAttachment`},
		paymentApproved: {name:`Payment Approved`, type:`checkbox`},
		reportApproved: {name:`Report Approved`, type:`checkbox`},
		customers: {name:`Customers`, type:`lookup`},
	},
};
